package cmd

import (
	"github.com/Andreagit97/bpftree/pkg/render"
	"github.com/Andreagit97/bpftree/pkg/task"
	"github.com/Andreagit97/bpftree/pkg/utils"
	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:     "bpftree",
	Short:   "bpftree - a simple CLI tool to inspect your system",
	Long:    `bpftree is a simple CLI tool to inspect your system`,
	Version: utils.GetToolVersion(),
}

// Execute is the entry point used for testing purposes.
func Execute() error {
	return rootCmd.Execute()
}

func init() {
	rootCmd.PersistentFlags().BoolVarP(&render.DisablePrettyPrint,
		"no-pretty",
		"n",
		false,
		"disable pretty-print mode")
	rootCmd.PersistentFlags().StringSliceVarP(&task.FormatFields,
		"format",
		"f",
		[]string{},
		`Render the task according to the provided fields.
Fields are separated by ',' (e.g. 'tid,pid,reaper') and DON'T have white spaces between them.`)
	rootCmd.PersistentFlags().StringVarP(&task.CaptureFilePath,
		"capture",
		"c",
		"",
		"Read task info from a capture file generated by a previous dump command.")
}
