// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package iterators

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadIter returns the embedded CollectionSpec for iter.
func loadIter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load iter: %w", err)
	}

	return spec, err
}

// loadIterObjects loads iter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*iterObjects
//	*iterPrograms
//	*iterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// iterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iterSpecs struct {
	iterProgramSpecs
	iterMapSpecs
}

// iterSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iterProgramSpecs struct {
	DumpTask     *ebpf.ProgramSpec `ebpf:"dump_task"`
	DumpTaskFile *ebpf.ProgramSpec `ebpf:"dump_task_file"`
}

// iterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iterMapSpecs struct {
}

// iterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIterObjects or ebpf.CollectionSpec.LoadAndAssign.
type iterObjects struct {
	iterPrograms
	iterMaps
}

func (o *iterObjects) Close() error {
	return _IterClose(
		&o.iterPrograms,
		&o.iterMaps,
	)
}

// iterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIterObjects or ebpf.CollectionSpec.LoadAndAssign.
type iterMaps struct {
}

func (m *iterMaps) Close() error {
	return _IterClose()
}

// iterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIterObjects or ebpf.CollectionSpec.LoadAndAssign.
type iterPrograms struct {
	DumpTask     *ebpf.Program `ebpf:"dump_task"`
	DumpTaskFile *ebpf.Program `ebpf:"dump_task_file"`
}

func (p *iterPrograms) Close() error {
	return _IterClose(
		p.DumpTask,
		p.DumpTaskFile,
	)
}

func _IterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iter_bpfeb.o
var _IterBytes []byte
