name: Linting
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: Lint golang files
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: |
          go generate ./...
          go build .
          go clean -modcache

      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          only-new-issues: false
          version: v1.59
          args: --timeout=900s

  gomodtidy:
    name: Enforce go.mod tidiness
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Execute go mod tidy and check the outcome
        working-directory: ./
        run: |
          go mod tidy
          exit_code=$(git diff --exit-code)
          exit ${exit_code}

      - name: Print a comment in case of failure
        run: |
          echo "The go.mod and/or go.sum files appear not to be correctly tidied.

          Please, rerun go mod tidy to fix the issues."
          exit 1
        if: |
          failure() && github.event.pull_request.head.repo.full_name == github.repository
