name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-all-archs:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To add assets to a release.
    steps:
      - name: Checkout commit
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Run GoReleaser
        id: run-goreleaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --release-notes=./release_changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
